(TeX-add-style-hook "chapter2"
 (lambda ()
    (LaTeX-add-labels
     "spatprocs"
     "R"
     "ximean"
     "cor"
     "fs1"
     "realcond"
     "xihatmean"
     "Sn"
     "homog"
     "spec"
     "cx"
     "fig:covspec"
     "a"
     "fig:correlation"
     "bdnr"
     "fig:square"
     "eq:square"
     "Mn"
     "sigma"
     "fig:R"
     "clt"
     "randlogmap"
     "fs2"
     "fig:rlogstable"
     "fig:envelope"
     "randcirc"
     "fig:rcircstable"
     "fs_circ")))

