(TeX-add-style-hook "chapter3"
 (lambda ()
    (LaTeX-add-labels
     "fig:rlogbif"
     "fig:rlogbif_zoom"
     "fig:rloglyap2"
     "fig:rloghist"
     "fig:rloghist2"
     "fig:rlogbif_hs"
     "fig:rloglyap2_hs"
     "fig:rloghist_hs"
     "fig:rloghist2_hs"
     "fig:rcirctongues_u"
     "fig:rcirctongues_u_ha"
     "fig:rcirclyap_u"
     "fig:rcirclyap2_u"
     "fig:rcirchist_u_ma1"
     "fig:rcirchist_u_ma2"
     "fig:avgcircorbs"
     "fig:rcirchist_u_ha1"
     "fig:rcirchist_u_ha2"
     "fig:randdevil1_u"
     "fig:randdevil2_u"
     "fig:kde1_u"
     "fig:rcirctongues_n"
     "fig:rcirctongues_n_ha"
     "fig:rcirclyap_n"
     "fig:rcirclyap_n_ha"
     "fig:rcirclyap2_n"
     "fig:randdevil1_n"
     "fig:randdevil2_n")))

