(TeX-add-style-hook "refs"
 (lambda ()
    (LaTeX-add-bibitems
     "neupauer"
     "hitczenko"
     "usgsgw"
     "gw"
     "basics"
     "geotechdata"
     "advection"
     "strogatz"
     "billingsley"
     "gelhar"
     "ross"
     "devaney"
     "meiss"
     "atkinson"
     "rasband"
     "athreya"
     "may"
     "dlb"
     "lamb"
     "janus"
     "UserGuide")))

